### ISSUE TITLE
Sharing the R2D2 Connection Pool Within the App

### ISSUE THREAD

**Issue by IdemenB** [rursprung/r2d2-oracle#11]
I need to create a DB connection pool in main.rs upon initilization of the app, keep the pool active forever and let it be used from within the functions that need an Oracle connection. The examples on the web stay mostly within a web framework (like Actix) scope and utilize the frameworks' capabilities to share some kind of global state or data.

In my use case, I don't use a web framework and my functions are in fact  "workers" with a standardized API running infinitely and handling some jobs by polling tasks from a workflow engine (each on a separate thread). Some of those functions need a Postgres connection, others Oracle, some both, and some do not make a DB connection at all, so passing pools as a parameter is not a good option.

For Postgres connections, I create the pool with SQLx crate and I use the once_cell crate to share from main.rs to other files. What do you think is the best way of sharing a R2D2 tool for this case?

Thanks a lot!

**Comment by rursprung** [comment]
this isn't an `r2d2-oracle` specific question as far as i can gather. i suggest you have a look at the [r2d2 docs](https://docs.rs/r2d2/0.8.9/r2d2/) or, if you don't find your information there, ask in the [r2d2 repo](https://github.com/sfackler/r2d2).
as you can see in the first example in the docs you can just call `clone()` on the pool and then hand that off to the thread you're starting.

if you're ok with this i'd propose to close this ticket here.

**Comment by IdemenB** [comment]
Sure @rursprung , sorry for the incorrect positioning of the question. I believe using once_cell, accessing it by getting a clone directly from within the function should work. I'll share the experience after trying.
