### ISSUE TITLE
I got a fatal error LNK1169

### ISSUE THREAD

**Issue by zhoujun681** [rursprung/r2d2-oracle#13]
error LNK1169:one or more multiply defined symbols found

**Comment by rursprung** [comment]
can you please provide some more information on how this can be reproduced?
which system are you testing on?
does this only happen with `r2d2-oracle` or also if you have `oracle` and/or `r2d2` alone?
can you please share your code (or even better: a stripped-down version thereof which serves as a reproducible case)?

**Comment by rursprung** [comment]
i'll close this for now since i haven't heard back from you. if you can provide the answers to the questions above and still think that it's related to this crate feel free to re-open this ticket (and provide the relevant information).
