### ISSUE TITLE
ERROR r2d2: OCI Error: ORA-28547: connection to server failed, probable Oracle Net admin error

### ISSUE THREAD

**Issue by shwahnim** [rursprung/r2d2-oracle#19]
I get this error when trying to shutdown the server, and the server hangs shutting down

**Comment by rursprung** [comment]
this doesn't seem to have anything to do with this library here (which is just a small glue code between [r2d2](https://github.com/sfackler/r2d2) (with which it also has nothing to do) and [oracle](https://github.com/kubo/rust-oracle). i'd suggest to raise your ticket in the oracle repository as this is the best place to get help with using the rust oracle driver.
however, it's likely that the error has nothing to do with the client implementation and instead is related to something else, in which case you'll have to consult the oracle documentation.
