### ISSUE TITLE
Loosen version requirement?

### ISSUE THREAD

**Issue by mlh758** [rursprung/r2d2-oracle#6]
Would it be possible to change the oracle version listed in Cargo.toml to just "0.3"? It would be nice to be able to pull in new patch versions without having to wait for this library to update.

**Comment by rursprung** [comment]
this is not needed, cargo handles `0.3.1` the same way as `^0.3.1`: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

thus any `oracle` version >= `0.3.1` and < `0.4` is acceptable and this library here doesn't need to be updated until oracle `0.4` or `1.0` comes out (in which case - according to [semver](https://semver.org/) - there will be breaking changes which might affect us).
we need an API introduced in `0.3.1` (see commit 117a291), thus we can't accept `0.3.0` and need to explicitly state this in the dependencies.

**Comment by mlh758** [comment]
Oh! I'm sorry about that, I misunderstood how the Cargo file specifies exact versions. Makes sense though.

**Comment by IdemenB** [comment]
Hi @rursprung , thank your for this pooling library.  I want to test both oracle and r2d2-oracle for our usecases and just noticed that oracle's version exceeded 0.5.0 (not it is 0.5.1.). Is that OK to update the dependency of your crate?

Additionaly, in the TODO list of the oracle crate they have "connection pooling" among others. Do they mean something else or are they not aware of this lib?

**Comment by rursprung** [comment]
the PR #9 should change the compatibility from `oracle 0.4` to `oracle 0.5`. i just haven't had time to review & merge it + create a new release of this crate. i'll get to it in the coming days. until then you'll have to stick to `oracle 0.4`.

**Comment by rursprung** [comment]
i've now released `r2d2-oracle v0.5.0` with support for `oracle v0.5`

> Additionaly, in the TODO list of the oracle crate they have "connection pooling" among others. Do they mean something else or are they not aware of this lib?

i raised kubo/rust-oracle#33 for this.
